definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  group.AllResponseItem:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  group.GetResponse:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  group.HistoryResponseItem:
    properties:
      contents:
        type: string
      iat:
        type: integer
      message_id:
        type: integer
      user_ident:
        type: string
    type: object
  group.PopularResponseItem:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  user.BioRequest:
    properties:
      bio:
        type: string
    type: object
  user.GetResponse:
    properties:
      bio:
        type: string
      display_name:
        type: string
      groups:
        items:
          $ref: '#/definitions/user.GetResponseGroup'
        type: array
      ident:
        type: string
    type: object
  user.GetResponseGroup:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  user.GroupsResponseItem:
    properties:
      group_id:
        type: integer
      name:
        type: string
    type: object
  user.JoinRequest:
    properties:
      group_id:
        type: integer
    type: object
  user.PostProfilePictureRequest:
    properties:
      jpeg:
        type: string
    type: object
  user.RegisterRequest:
    properties:
      display_name:
        type: string
      email:
        type: string
      password:
        type: string
    type: object
  user.RegisterResponse:
    properties:
      ident:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      description: Log in to user and authenticate with the backend
      parameters:
      - description: User login information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Login user
      tags:
      - auth
  /course/department/{dep}:
    get:
      description: Queries for all UF courses in a three-letter department prefix
      parameters:
      - description: Three-letter department prefix
        in: path
        name: dep
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
        "503":
          description: Service Unavailable
      summary: Get courses in department
      tags:
      - course
  /course/group/{dep}/{code}:
    get:
      description: Gets (or creates) group of specified course
      parameters:
      - description: Three-letter department prefix
        in: path
        name: dep
        required: true
        type: string
      - description: Four-digit (with potential postfix) course code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
        "503":
          description: Service Unavailable
      summary: Get group of specified course
      tags:
      - course
  /group/all:
    get:
      description: Gets all public groups
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/group.AllResponseItem'
            type: array
        "500":
          description: Internal Server Error
      summary: Gets groups
      tags:
      - group
  /group/get/{id}:
    get:
      description: Gets group information
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/group.GetResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get group
      tags:
      - group
  /group/history/{id}:
    get:
      description: Gets message history from a group in descending order
      parameters:
      - description: Group ID
        in: path
        name: id
        required: true
        type: integer
      - description: Max number of messages to retreive (<= 20)
        in: query
        name: limit
        required: true
        type: integer
      - description: UTC time cutoff; searches in reverse from this point (inclusive)
        in: query
        name: before
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/group.HistoryResponseItem'
            type: array
        "500":
          description: Internal Server Error
      summary: Gets group messages
      tags:
      - group
  /group/popular/{count}:
    get:
      description: Gets the most popular groups by member count
      parameters:
      - description: Count of groups to return
        in: path
        name: count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/group.PopularResponseItem'
            type: array
        "500":
          description: Internal Server Error
      summary: Gets popular groups
      tags:
      - group
  /user/bio:
    post:
      description: Updates a user's bio
      parameters:
      - description: New bio
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.BioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Updates bio
      tags:
      - user
  /user/get/{ident}:
    get:
      description: Fetches publically available user information and groups.
      parameters:
      - description: User identifier
        in: path
        name: ident
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.GetResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Fetch user
      tags:
      - user
  /user/groups:
    get:
      description: Returns all groups a user belongs to
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.GroupsResponseItem'
            type: array
        "500":
          description: Internal Server Error
      summary: Get groups
      tags:
      - user
  /user/join:
    post:
      description: Adds a user to a group
      parameters:
      - description: Group to join
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.JoinRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Join group
      tags:
      - user
  /user/leave:
    post:
      description: Removes a user from a group
      parameters:
      - description: Group to leave
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.JoinRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Leave group
      tags:
      - user
  /user/profile_picture:
    post:
      description: Uploads a new profile picture, replacing the old one
      parameters:
      - description: New profile picture
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.PostProfilePictureRequest'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Upload profile picture
      tags:
      - user
  /user/profile_picture/{ident}:
    get:
      description: Gets a user's profile picture from their identifier
      parameters:
      - description: User identifier
        in: path
        name: ident
        required: true
        type: string
      produces:
      - image/jpeg
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Retrieves profile picture
      tags:
      - user
  /user/register:
    post:
      description: Registers a new user given the provided arguments
      parameters:
      - description: User registration information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.RegisterResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Register a new user
      tags:
      - user
  /ws/{group}:
    get:
      description: Opens a WebSocket for a user on a group
      parameters:
      - description: Group ID
        in: path
        name: group
        required: true
        type: integer
      responses:
        "401":
          description: Unauthorized
      summary: Opens a WebSocket
      tags:
      - ws
swagger: "2.0"
