//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type UserAccount struct {
	ID          int64 `sql:"primary_key"`
	Identifier  string
	DisplayName string
	Hash        string
	Email       string
	Bio         *string
}
